language: php

php:
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"

sudo: false

before_install:
  # If PHP >= 7.0, force use of PHPunit 5.7
  - if php -r "exit( (int)! version_compare( '$TRAVIS_PHP_VERSION', '7.0', '>=' ) );"; then mkdir ~/bin && wget -O ~/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar && chmod +x ~/bin/phpunit; fi

before_script:
  - composer install

script:
  - phpunit --configuration tests/phpunit.xml
