language: php

php:
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"

sudo: false

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:1.* squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

script:
  - phpunit --configuration tests/phpunit.xml
